version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LOG_DIRS: /var/lib/kafka/data

  kafka-tools:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-tools
    depends_on:
      - kafka
    entrypoint: /bin/bash
    command: -c "echo 'Waiting for Kafka to start...'; while ! kafka-topics --list --bootstrap-server kafka:9092; do sleep 1; done; echo 'Kafka started.'; sleep infinity"
